name: mvc_template
description: Flutter MVC pattern template 
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  freezed_annotation: ^2.2.0
  get_it: ^7.6.0
  injectable: ^2.1.2
  bloc: any
  flutter_bloc: ^8.1.3
  hydrated_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.4
  injectable_generator: ^2.1.6
  freezed: ^2.3.4
  dart_code_metrics: ^5.7.4
  dart_code_metrics_presets: ^1.8.0

flutter:
  uses-material-design: true
